# designer-guard.ps1 -- PreToolUse hook.
#
# WinForms designer-owned files. Hand-editing them is occasionally correct and usually a mistake,
# so this asks rather than blocks: it returns permissionDecision "ask" and lets the user decide.
#
# Guarded, and only under Source\ (excluding \Apps\), and only when the file already exists:
#
#   *.Designer.vb   17 files. Regenerated wholesale by the Visual Studio designer -- a hand edit
#                   survives only until someone opens the form, then is silently overwritten.
#   *.resx          51 files. Every one carries real base64 <data> payloads of serialized objects;
#                   a careless edit corrupts them in a way that surfaces at runtime, not build time.
#
# The scoping matters. Creating a brand-new .resx overwrites nothing, and a .resx in an unrelated
# checkout or under Source\Apps\ has no designer behind it. Prompting on those teaches the user to
# approve without reading, which is how the guard stops working on the files that do matter.
#
# Deliberately NOT guarded: Source/Forms/MainForm.vb. It has no .Designer.vb at all -- its
# ~880-line InitializeComponent() is hand-written and hand-edited by design.
#
# Two modes, both wired up in .claude/settings.json:
#
#   (default)   Edit|Write        check tool_input.file_path
#   -Command    Bash|PowerShell   check paths named in tool_input.command, because a shell
#                                 redirect edits these files without going through Edit|Write
#
# Escape hatch: set STAXRIP_ALLOW_DESIGNER_EDIT=1 to skip the prompt entirely.

[CmdletBinding()]
param([switch] $Command)

$ErrorActionPreference = 'Stop'

if ($env:STAXRIP_ALLOW_DESIGNER_EDIT -eq '1') { exit 0 }

try {
    $raw = [Console]::In.ReadToEnd()
    if ([string]::IsNullOrWhiteSpace($raw)) { exit 0 }
    $payload = $raw | ConvertFrom-Json
} catch {
    exit 0
}

$projectDir = $env:CLAUDE_PROJECT_DIR
if (-not $projectDir) { $projectDir = (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) }

#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

function Resolve-Candidate {
    param([string] $Path)

    if ([string]::IsNullOrWhiteSpace($Path)) { return $null }

    $normalized = $Path.Trim().Trim('"', "'") -replace '/', '\'
    if (-not [IO.Path]::IsPathRooted($normalized)) {
        $normalized = Join-Path $projectDir $normalized
    }

    # Must already exist: a Write that creates the file is not overwriting designer output.
    if (-not (Test-Path -LiteralPath $normalized -PathType Leaf)) { return $null }

    try {
        return (Resolve-Path -LiteralPath $normalized).Path
    } catch {
        return $null
    }
}

function Get-GuardKind {
    param([string] $FullPath)

    if ($FullPath -notmatch '(?i)\\Source\\') { return $null }
    if ($FullPath -match '(?i)\\Apps\\') { return $null }

    $leaf = Split-Path -Leaf $FullPath
    if ($leaf -match '(?i)\.Designer\.vb$') { return 'designer' }
    if ($leaf -match '(?i)\.resx$') { return 'resx' }
    return $null
}

#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Collect candidates

$candidates = [Collections.Generic.List[string]]::new()

if ($Command) {
    $commandText = $payload.tool_input.command
    if ([string]::IsNullOrWhiteSpace($commandText)) { exit 0 }

    # Path-ish tokens ending in a guarded extension. Deliberately loose: a false positive here
    # costs one prompt, a false negative silently corrupts a .resx.
    foreach ($m in [regex]::Matches($commandText, '(?i)[\w.\\/:$-]*\.(?:Designer\.vb|resx)\b')) {
        $resolved = Resolve-Candidate -Path $m.Value
        if ($resolved) { $candidates.Add($resolved) }
    }
} else {
    $resolved = Resolve-Candidate -Path $payload.tool_input.file_path
    if ($resolved) { $candidates.Add($resolved) }
}

$guarded = @(
    $candidates | Sort-Object -Unique | ForEach-Object {
        $kind = Get-GuardKind -FullPath $_
        if ($kind) { [pscustomobject]@{ Path = $_; Kind = $kind; Leaf = (Split-Path -Leaf $_) } }
    }
)

if ($guarded.Count -eq 0) { exit 0 }

#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Ask

$names = ($guarded | ForEach-Object { $_.Leaf }) -join ', '

$reason = if ($guarded | Where-Object { $_.Kind -eq 'designer' }) {
    "$names is generated by the Visual Studio WinForms designer. Edits here are overwritten the " +
    "next time anyone opens the form in the designer, so a fix made here can silently disappear. " +
    "Prefer changing the form's own .vb file, or make the change through the designer. " +
    "(MainForm.vb is different -- it has no designer file and is edited by hand.)"
} else {
    "$names is a designer-owned resource file containing base64-serialized object payloads. " +
    "Hand-editing risks corrupting those in a way that fails at runtime rather than at build time, " +
    "and the designer may rewrite the file anyway."
}

if ($Command) {
    $reason += " This is being written through a shell command rather than Edit/Write."
}

$response = @{
    hookSpecificOutput = @{
        hookEventName            = 'PreToolUse'
        permissionDecision       = 'ask'
        permissionDecisionReason = $reason
    }
} | ConvertTo-Json -Depth 5 -Compress

Write-Output $response
exit 0
